version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  api:
    container_name: bubble-share
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.native-micro
    image: bubble-share
    depends_on:
      - db
    ports:
      - '443:443'
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
    volumes:
      - './:/src'
      - './bubble-share-firebase-adminsdk-wee7c-caf1cd974b.json:/work/bubble-share-firebase-adminsdk-wee7c-caf1cd974b.json'
      - './keystore.jks:/work/keystore.jks'
volumes:
  db:
    driver: local
