mp.jwt.verify:
  issuer: "https://securetoken.google.com/bubble-share"
  verify.publickey.location: "META-INF/resources/key.pem"
quarkus:
  smallrye-jwt:
    enabled: "true"
  hibernate-orm:
    database:
      generation: "drop-and-create"
    sql-load-script: ["import.sql"]
quarkus.datasource:
  db-kind: "h2"

bubbleshare:
  serviceKeyLocation: "bubble-share-firebase-adminsdk-wee7c-caf1cd974b.json"
