greeting:
  message: "hello"

mp.jwt.verify:
  issuer: "https://securetoken.google.com/bubble-share"
  verify.publickey.location: "META-INF/resources/key.pem"
quarkus:
  smallrye-jwt:
    enabled: "true"

quarkus.datasource:
  db-kind: "h2"
