name: build-native-docker-and-deploy
on:
  push:
    branches:
      - main
jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build native Quarkus app
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Build native executable and upload it as an artifact
        uses: maxday/quarkus-native-build-docker-action@1
        with:
          outputName: bubble-share-runner
          dockerfilePath: src/main/docker/Dockerfile.native-micro
